<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An error occurred while installing Rights.' => 'Ein Fehler ist aufgetreten, während der Installation von Rights',
  'Application authorization manager must extend the RDbAuthManager class.' => '',
  'Application web user must extend the RWebUser class.' => '',
  'Congratulations!' => 'Gratulation!',
  'Error' => 'Fehler',
  'Install Rights' => 'Installiere Rights',
  'No' => 'Nein',
  'Notice: All your existing data will be lost.' => 'Achtung: Alle Daten gehen verloren',
  'Please confirm if you wish to reinstall.' => 'Bitte bestätigen, wenn du die Installation wiederholen willst',
  'Please try again or consult the documentation.' => 'Bitte wiederholen und die Dokumenation lesen.',
  'Rights has been installed succesfully.' => 'Rights wurde erfolgreich installiert.',
  'Rights is already installed!' => 'Rights ist bereits installiert!',
  'Yes' => 'Ja',
  'You can start by generating your authorization items' => 'Du kannst damit beginnen, deine Berechtigungs-Elemente zu erstellen',
  'You must be logged in to install Rights.' => 'Du musst eingeloggt sein, um Rights zu installieren.',
  'here' => 'hier',
);
